; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-display]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
build_type = debug
monitor_speed = 115200
monitor_filters =
        default
        time
        esp32_exception_decoder
build_flags =
        -DDEBUG_MODE_ENABLED=0
        -DCORE_DEBUG_LEVEL=0
        -DLMIC_DEBUG_LEVEL=0

lib_deps = 
        Wire
        https://github.com/plerup/espsoftwareserial.git
        
